### P16 nn.Module的使用

In [2]:
import torch
from torch import nn

class Tudui(nn.Module):
    def __init__(self):
        super().__init__()
        #self.linear = nn.Linear(1, 1)

    def forward(self, input):
        output = input * 2
        return output
    
tudui = Tudui()
tudui(torch.tensor([1.0]))

tensor([2.])

### P17 土说卷积操作

In [15]:
import torch
import torch.nn.functional as F

input = torch.tensor([[1, 2, 0, 3, 1],
                      [0, 1, 2, 3, 1],
                      [1, 2, 1, 0, 0],
                      [5, 2, 3, 1, 1],
                      [2, 1, 0, 1, 1]])
kernal = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [2, 1, 0]])

input = torch.reshape(input, (1, 1, 5, 5))
kernal = torch.reshape(kernal, (1, 1, 3, 3))
input, kernal

output = F.conv2d(input, kernal, stride=1, padding=1)

output2 = F.conv2d(input, kernal, stride=2, padding=2)

output, output2

(tensor([[[[ 1,  3,  4, 10,  8],
           [ 5, 10, 12, 12,  6],
           [ 7, 18, 16, 16,  8],
           [11, 13,  9,  3,  4],
           [14, 13,  9,  7,  4]]]]),
 tensor([[[[ 0,  4,  3,  2],
           [ 1, 10, 12,  1],
           [ 1, 13,  3,  2],
           [ 2,  4,  3,  1]]]]))

### P18 卷积层

In [39]:
import torch
import torchvision
from torch import nn
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10(root='./data', train=False, transform=torchvision.transforms.ToTensor(), download=True)

dataloader = DataLoader(dataset, batch_size=64)

class Tudui(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 3, stride=1, padding=0)

    def forward(self, input):
        output = self.conv1(input)
        return output
    
tudui = Tudui()

writer = SummaryWriter('./logs')

step = 0
for data in dataloader:
    img, label = data
    output = tudui(img)
    # print(img.shape)
    # print(output.shape)

    # torch.Size([64, 3, 32, 32])
    writer.add_images('input', img, step)


    # torch.Size([64, 6, 30, 30])
    output = torch.reshape(output, (-1, 3, 30, 30))
    writer.add_images('output', output, step)

    step = step + 1

Files already downloaded and verified


### P19 最大池化层

In [48]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10(root='./data', train=False, transform=torchvision.transforms.ToTensor(), download=True)

dataloader = DataLoader(dataset, batch_size=64)
# input = torch.tensor([[1, 2, 0, 3, 1],
#                       [0, 1, 2, 3, 1],
#                       [1, 2, 1, 0, 0],
#                       [5, 2, 3, 1, 1],
#                       [2, 1, 0, 1, 1]], dtype=torch.float32)

# input= torch.reshape(input, (1, 1, 5, 5)) # (batch, channel, height, width)

# MaxPool
class Tudui(nn.Module):
    def __init__(self):
        super().__init__()
        self.pool = nn.MaxPool2d(2, ceil_mode=False) 
    
    def forward(self, input):
        output = self.pool(input)
        return output
    
tudui = Tudui()

writer = SummaryWriter('./logs_MaxPool')
step = 0
for data in dataloader:
    img, label = data
    writer.add_images('input', img, step)
    output = tudui(img)
    writer.add_images('output', output, step)
    step = step + 1

Files already downloaded and verified


### P20 非线性激活函数

In [62]:
import torch
import torchvision
from torch import nn
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

# input = torch.tensor([[1, -0.5],
#                        [-1, 3]], dtype=torch.float32)

# output = torch.reshape(input, (1, 1, 2, 2))

dataset = torchvision.datasets.CIFAR10(root='./data', train=False, transform=torchvision.transforms.ToTensor(), download=True)
dataloader = DataLoader(dataset, batch_size=64)

# ReLU and Sigmoid
class Tudui(nn.Module):
    def __init__(self):
        super().__init__()
        # self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, input):
        # output = self.relu(input)
        output = self.sigmoid(input)
        return output
    
tudui = Tudui()
writer = SummaryWriter('./logs_ReLU_Sigmoid')


step = 0
for data in dataloader:
    imgs, label = data
    writer.add_images('input', imgs, global_step=step)
    output = tudui(imgs)
    writer.add_images('output', output, step)
    step = step + 1
    
writer.close()

Files already downloaded and verified


### P21 线性层及其他层介绍

In [70]:
import torch
import torchvision
from torch import nn
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10(root='./data', train=False, transform=torchvision.transforms.ToTensor(), download=True)

dataloader = DataLoader(dataset, batch_size=64)

class Tudui(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(196608, 10)

    def forward(self, input):
        output = self.linear(input)
        return output

tudui = Tudui()
for data in dataloader:
    img, label = data
    print(img.shape)
    # output = torch.reshape(img, (1, 1, 1, -1))
    output = torch.flatten(img)
    print(output.shape)
    output = tudui(output)
    print(output.shape)
    break

Files already downloaded and verified
torch.Size([64, 3, 32, 32])
torch.Size([196608])
torch.Size([10])
